### PR TITLE
fix(tests): replace golang mock by uber-go mock

### PR DESCRIPTION
**Pull request by katsuharu**
Hi there! 👋

I've created a pull request  to address the issue https://github.com/eko/gocache/issues/248. In this PR, I've implemented the following changes:

- replace https://github.com/golang/mock to https://github.com/uber-go/mock

Please review the changes and let me know if there's anything else needed or if further adjustments are required. Looking forward to your feedback!

Thank you!

### CODE REVIEW

**Review by eko — APPROVED** [review]
Thank you for the update @katsuharu

**Comment by eko** [comment]
Could you please just rebase with the master branch? I've updated library to `v4.1.6` on all stores so there is a conflict on `go.mod` now.

Thank you!

**Comment by katsuharu** [comment]
@eko 
Thank you for your review! 

Sure, I’ll rebase with the master branch and resolve the conflict.

**Comment by katsuharu** [comment]
@eko 
Thank you for your feedback! I've rebased the changes as requested and pushed the updates to the PR. Please take another look at your earliest convenience.

**Comment by eko** [comment]
Thank you @katsuharu!

**Pull request merged**
