### PR TITLE
add standard not found error

### LINKED ISSUE #141: Common not found error or different `get()` signature
What are your thoughts on a common `gocache.NotFound` error that wraps the store not found error classes if there is one. Right now its a bit of a leaky abstraction when using multiple cache types as they have different not found errors ie `bigcache.ErrEntryNotFound` vs `redis.Nil`. Alternatively we could add a found bool get() signature. `entry, isFound, nil := cache.Get(...)`. Willing to submit a pr.

### PR DESCRIPTION
**Pull request by Ashtonian**
resolves #141

### CODE REVIEW

**Review by eko — COMMENTED** [review]
Could you please also update unit tests? They are failing actually:

```bash
=== RUN   TestFreecacheGetNotFound
    freecache_test.go:81:
        	Error Trace:	freecache_test.go:81
        	Error:      	Error message not equal:
        	            	expected: "value not found in Freecache store"
        	            	actual  : "Value not found in store"
        	Test:       	TestFreecacheGetNotFound
--- FAIL: TestFreecacheGetNotFound (0.00s)
=== RUN   TestFreecacheGetWithTTLWhenMissingItem
    freecache_test.go:144:
        	Error Trace:	freecache_test.go:144
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"value not found in Freecache store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc0001bbe40)})
        	Test:       	TestFreecacheGetWithTTLWhenMissingItem
--- FAIL: TestFreecacheGetWithTTLWhenMissingItem (0.00s)
=== RUN   TestFreecacheGetWithTTLWhenErrorAtTTL
    freecache_test.go:170:
        	Error Trace:	freecache_test.go:170
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"value not found in Freecache store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc000206050)})
        	Test:       	TestFreecacheGetWithTTLWhenErrorAtTTL
--- FAIL: TestFreecacheGetWithTTLWhenErrorAtTTL (0.00s)
=== RUN   TestGoCacheGetWhenError
    go_cache_test.go:74:
        	Error Trace:	go_cache_test.go:74
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"Value not found in GoCache store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc000207c50)})
        	Test:       	TestGoCacheGetWhenError
--- FAIL: TestGoCacheGetWhenError (0.00s)
=== RUN   TestGoCacheGetWithTTLWhenError
    go_cache_test.go:118:
        	Error Trace:	go_cache_test.go:118
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"Value not found in GoCache store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc000207f20)})
        	Test:       	TestGoCacheGetWithTTLWhenError
=== RUN   TestRistrettoGetWhenError
    ristretto_test.go:73:
        	Error Trace:	ristretto_test.go:73
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"Value not found in Ristretto store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc000a768b0)})
        	Test:       	TestRistrettoGetWhenError
--- FAIL: TestRistrettoGetWhenError (0.00s)
=== RUN   TestRistrettoGetWithTTLWhenError
    ristretto_test.go:117:
        	Error Trace:	ristretto_test.go:117
        	Error:      	Not equal:
        	            	expected: *errors.errorString(&errors.errorString{s:"Value not found in Ristretto store"})
        	            	actual  : store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc000a76b80)})
        	Test:       	TestRistrettoGetWithTTLWhenError
--- FAIL: TestRistrettoGetWithTTLWhenError (0.00s)
```

Also, sometimes errors are double-wrapped, ie: `store.NotFound(store.NotFound{cause:(*errors.errorString)(0xc0001bbe40)})`.

I think it should not be the case.

Thank you for your time on this subject.

**Comment by Ashtonian** [comment]
Will fix, how should I deal with generic changes on master, I think those are breaking changes?, would like these changes to be in current version if possible.

**Comment by eko** [comment]
You're right, there will be a breaking change with generics support, that's why I will release a `v3.0.0` with this (and option pattern I'm reworking currently).

You can rebase with master branch, merge this feature on master branch and I will backport your feature on [v2](https://github.com/eko/gocache/tree/v2) branch and make a new v2 release with your updates.

**Comment by agonzalezro** [comment]
Hi @eko, I hit the same issue and I would be happy to fix the tests in case @Ashtonian doesn't have the time. Please let me know.

**Comment by Ashtonian** [comment]
I think this is fixed?

**Comment by eko** [comment]
I'm sorry but it looks like tests are still failing: https://github.com/eko/gocache/runs/6833054341?check_suite_focus=true#step:5:301

Let me know if you want to me to take a look.

**Comment by eko** [comment]
I'm sorry but it looks like tests are still failing: https://github.com/eko/gocache/runs/6833054341?check_suite_focus=true#step:5:301

Let me know if you want to me to take a look.

**Comment by Ashtonian** [comment]
sorry about that, fixed.

**Review by eko — APPROVED** [review]

**Comment by eko** [comment]
Thank you for fixing the issues and you work on this subject @Ashtonian!

**Pull request merged**
