### PR TITLE
support github.com/patrickmn/go-cache

### PR DESCRIPTION
**Pull request by fmyxyz**

### CODE REVIEW

**Comment by fmyxyz** [comment]
Can you guide me to fix them ?
@eko

**Comment by eko** [comment]
Hi @fmyxyz, alright I will take a look as soon as possible.

**Comment by eko** [comment]
Hi @fmyxyz, it seems that tests are working great, I have issues with Travis-CI and will migrate to GitHub Actions as soon as possible.

Anyway, it's OK for me :)

Could I merge your addition?

**Comment by fmyxyz** [comment]
sure

**Comment by eko** [comment]
Thank you! I will create a new release with your addition

**Pull request merged**
